/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ContactDto } from '../../models/contact-dto';

export interface FindContactById$Params {
  contact_id: number;
}

export function findContactById(http: HttpClient, rootUrl: string, params: FindContactById$Params, context?: HttpContext): Observable<StrictHttpResponse<ContactDto>> {
  const rb = new RequestBuilder(rootUrl, findContactById.PATH, 'get');
  if (params) {
    rb.path('contact_id', params.contact_id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ContactDto>;
    })
  );
}

findContactById.PATH = '/contacts/{contact_id}';
