/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NgModule, ModuleWithProviders, SkipSelf, Optional } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { ApiConfiguration, ApiConfigurationParams } from './api-configuration';

import { UserService } from './services/user.service';
import { TransactionService } from './services/transaction.service';
import { ContactService } from './services/contact.service';
import { AuthenticationService } from './services/authentication.service';
import { AddressService } from './services/address.service';
import { AccountService } from './services/account.service';
import { RoleService } from './services/role.service';
import { HttpInterceptorComponent } from './http-interceptor/http-interceptor/http-interceptor.component';
import { AdminGuardComponent } from './guard/admin-guard/admin-guard.component';

/**
 * Module that provides all services and configuration.
 */
@NgModule({
  imports: [],
  exports: [],
  declarations: [
    HttpInterceptorComponent,
    AdminGuardComponent
  ],
  providers: [
    UserService,
    TransactionService,
    ContactService,
    AuthenticationService,
    AddressService,
    AccountService,
    RoleService,
    ApiConfiguration
  ],
})
export class ApiModule {
  static forRoot(params: ApiConfigurationParams): ModuleWithProviders<ApiModule> {
    return {
      ngModule: ApiModule,
      providers: [
        {
          provide: ApiConfiguration,
          useValue: params
        }
      ]
    }
  }

  constructor( 
    @Optional() @SkipSelf() parentModule: ApiModule,
    @Optional() http: HttpClient
  ) {
    if (parentModule) {
      throw new Error('ApiModule is already loaded. Import in your base AppModule only.');
    }
    if (!http) {
      throw new Error('You need to import the HttpClientModule in your AppModule! \n' +
      'See also https://github.com/angular/angular/issues/20575');
    }
  }
}
